### ISSUE TITLE
Allow adding custom headers

### ISSUE THREAD

**Issue by Barbapapazes** [adonisjs/transmit-client#3]
### Package version

0.1.5

### Describe the bug

Hello,

I need to connect to an authorize channel using an OAT. Could be easier to do by having an access to the header of the subscribe request.

https://github.com/adonisjs/transmit-client/blob/main/src/transmit.ts#L189

**Comment by Barbapapazes** [comment]
Maybe you recommend to do it by using the `beforeUnsubscribe` hook?

**Comment by Barbapapazes** [comment]
Cannot use the header property.

```
Uncaught (in promise) TypeError: Cannot set property headers of #<Request> which has only a getter
```

**Comment by Barbapapazes** [comment]
It works but there is a type issue.

![image](https://github.com/adonisjs/transmit-client/assets/45267552/a84d7487-f906-4d5b-9fe0-cac427a6a015)

**Comment by Barbapapazes** [comment]
Shouldn't be this type, https://github.com/adonisjs/transmit-client/blob/main/src/transmit.ts#L4, a `Request`?

**Comment by RomainLanz** [comment]
> Maybe you recommend to do it by using the `beforeSubscribe` hook?

Yes, you can alter the request with the `beforeSubscribe` hook.

> Shouldn't be this type, https://github.com/adonisjs/transmit-client/blob/main/src/transmit.ts#L4, a `Request`?

Correct. May you send a PR?

**Comment by RomainLanz** [comment]
Done https://github.com/adonisjs/transmit-client/releases/tag/v0.2.0
