### ISSUE TITLE
EventSource failed loading

### ISSUE THREAD

**Issue by Steveperi** [adonisjs/transmit-client#4]
### Package version

adonis 6

### Describe the bug

Hello 
I have the following error:
![Screenshot 2024-04-10 at 11 19 35 AM](https://github.com/adonisjs/transmit-client/assets/6014414/8df06c84-ed32-48ca-b085-d8be5043c64c)

Thank you

**Comment by RomainLanz** [comment]
Have you installed the backend service?

**Comment by RomainLanz** [comment]
Can you please show your `.adonisrc.ts` file?

**Comment by Steveperi** [comment]
> Can you please show your `.adonisrc.ts` file?

Yes, here is screenshoot from my file
![Screenshot 2024-04-10 at 11 28 27 AM](https://github.com/adonisjs/transmit-client/assets/6014414/86c48a61-950d-419e-a79e-f8b7546d26e5)

**Comment by RomainLanz** [comment]
Mmmh, you can please list your routes with `node ace list:routes`?

**Comment by Steveperi** [comment]
> Mmmh, you can please list your routes with `node ace list:routes`?

Yes of course
![Screenshot 2024-04-10 at 11 33 34 AM](https://github.com/adonisjs/transmit-client/assets/6014414/555457e5-6367-4275-9140-b379167c829f)

**Comment by RomainLanz** [comment]
It means the route exists. Everything is correctly registered on your backend.
Last idea I have is the port, are you running your backend on the `3333` port?

**Comment by Steveperi** [comment]
> It means the route exists. Everything is correctly registered on your backend. The last idea I have is the port. Are you running your backend on the `3333` port?

Yes I'm running on port 3333

**Comment by RomainLanz** [comment]
I wonder if the `domain` setup you made created the issue.

I will update the backend package to allow the definition of a domain when registering the route.
In the meantime, can you create a repository with the minimum amount of code to reproduce the issue?

**Comment by Steveperi** [comment]
> I wonder if the `domain` setup you made created the issue.
> 
> I will update the backend package to allow the definition of a domain when registering the route. In the meantime, can you create a repository with the minimum amount of code to reproduce the issue?

I created a new project. Here is my repository [repo](https://github.com/Steveperi/adonis-transmit)
When I setup the route with this code 
```
router.get('/', '#controllers/sites_controller.index').domain(process.env.SITE_DOMAIN!)
```
 transmit doesn't work, but it works when remove 
```
.domain(process.env.SITE_DOMAIN!)
```

Thank you

**Comment by RomainLanz** [comment]
Cool, so it seems the issue is the `domain` setup.
May you create an issue in the backend repository?

**Comment by Steveperi** [comment]
> Cool, so it seems the issue is the `domain` setup. May you create an issue in the backend repository?

Ok. Thank you for your time
