### ISSUE TITLE
How to use in a react-native app

### ISSUE THREAD

**Issue by oyepez003** [adonisjs/transmit-client#7]
### Package version

any

### Describe the bug

Is there a plan to document how to work using transmit-client in applications different to a web-app? like a react-native app.

In a React web-app its working as expected but in react native it doesn't work...

**Comment by RomainLanz** [comment]
Hey @oyepez003! 👋🏻 

Since React Native runs in another runtime, you will probably have to swap some dependencies to make it work properly.

To specify which polyfill/package to use, you will need to use the `eventSourceFactory` and `eventTargetFactory` configuration options.

You can have a look at [react-native-event-source](https://www.npmjs.com/package/react-native-event-source) for example.

**Comment by oyepez003** [comment]
Thanks for your answer @RomainLanz I tried with that library and react-native-sse but I couldn't make it work... 

I'm moving the implementation to WebSockets, but I keep watching this project. I think, transmit is an amazing extra for AdonisJS.

Thanks again.

**Comment by pgnonick** [comment]
Hi,
i also tried it and here my experience and solution and I want to share it. 

First error was EventSource is undefined, so I used the factory and replaced it with react-native-sse. Next error EventTarget is undefined, so I replaced it with a shim through the factory option. Then crypto is not defined, then I replaced the uid generator with the extra option. But then CustomEvent and URL is not defined and this cannot easy replaced. So currently I would say transmit-client is not usable for react-native.

So I rollbacked everything on my react-native app and only installed react-native-sse and I did a small rebuild of the transmit-client by checking the code, what is happening.

With this code it is basically working in react native, next step should be to refactor and make a usable service class:

```
import { useEffect } from "react";
import { Image, StyleSheet, Platform } from "react-native";
import EventSource from "react-native-sse";
import uuid from "react-native-uuid";

import { HelloWave } from "@/components/HelloWave";
import ParallaxScrollView from "@/components/ParallaxScrollView";
import { ThemedText } from "@/components/ThemedText";
import { ThemedView } from "@/components/ThemedView";

export default function HomeScreen() {
  useEffect(() => {
    console.log("INIT")
    const uid = uuid.v4();
    const es = new EventSource('http://localhost:3333/__transmit/events?uid=' + uid);

    es.addEventListener("open", async (event) => {
      console.log("Open SSE connection.");

      const res = await fetch('http://localhost:3333/__transmit/subscribe', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ uid, channel: 'global' }),
        credentials: 'include',
      })

      if (res.ok) {
        console.log("Subscribed")
        es.addEventListener("message", (event) => {
          console.log("New message event:", event.data);
        });
      } else {
        console.log("ERROR");
        es.removeAllEventListeners();
      }
    });

    return () => {
      console.log("REMOVE");
      es.removeAllEventListeners();
    };
  }, []);

  return (
    <ParallaxScrollView
      headerBackgroundColor={{ light: "#A1CEDC", dark: "#1D3D47" }}
      headerImage={
        <Image
          source={require("@/assets/images/partial-react-logo.png")}
          style={styles.reactLogo}
        />
      }
    >
      <ThemedView style={styles.titleContainer}>
        <ThemedText type="title">Welcome!</ThemedText>
        <HelloWave />
      </ThemedView>
      <ThemedView style={styles.stepContainer}>
        <ThemedText type="subtitle">Step 1: Try it</ThemedText>
        <ThemedText>
          Edit{" "}
          <ThemedText type="defaultSemiBold">app/(tabs)/index.tsx</ThemedText>{" "}
          to see changes. Press{" "}
          <ThemedText type="defaultSemiBold">
            {Platform.select({ ios: "cmd + d", android: "cmd + m" })}
          </ThemedText>{" "}
          to open developer tools.
        </ThemedText>
      </ThemedView>
      <ThemedView style={styles.stepContainer}>
        <ThemedText type="subtitle">Step 2: Explore</ThemedText>
        <ThemedText>
          Tap the Explore tab to learn more about what's included in this
          starter app.
        </ThemedText>
      </ThemedView>
      <ThemedView style={styles.stepContainer}>
        <ThemedText type="subtitle">Step 3: Get a fresh start</ThemedText>
        <ThemedText>
          When you're ready, run{" "}
          <ThemedText type="defaultSemiBold">npm run reset-project</ThemedText>{" "}
          to get a fresh <ThemedText type="defaultSemiBold">app</ThemedText>{" "}
          directory. This will move the current{" "}
          <ThemedText type="defaultSemiBold">app</ThemedText> to{" "}
          <ThemedText type="defaultSemiBold">app-example</ThemedText>.
        </ThemedText>
      </ThemedView>
    </ParallaxScrollView>
  );
}

const styles = StyleSheet.create({
  titleContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  stepContainer: {
    gap: 8,
    marginBottom: 8,
  },
  reactLogo: {
    height: 178,
    width: 290,
    bottom: 0,
    left: 0,
    position: "absolute",
  },
});
```

IMPORTANT: This solution is currently not working with csrf and session protection. I added __transmit as excepted route for csrf. And I have not checked yet if token auth is working with transmit, which should be the next step for secured channels.

I hope, this can help other devs with react native apps.

**Comment by oyepez003** [comment]
Hi @rzwinge! Thanks for sharing an approach solution for the issue.

- Yes, token auth is working with transmit, there is no problem with that.
